name: push_nuget

on:
  push:
    branches: [ master ]        # or main, match your repo’s default branch
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Only needed if you want the action to build your csproj before packing the .nuspec
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2

      - name: Publish VL Nuget
        uses: vvvv/PublishVLNuget@1.0.43
        with:
          # Build your DLLs from the csproj (recommended)
          csproj: src\VL.Assimp\VL.Assimp.csproj
          # Then pack/publish using your nuspec
          nuspec: deployment\VL.Assimp.nuspec
          # Optional icon fetch (keeps your repo clean)
          icon-src: https://raw.githubusercontent.com/vvvv/PublicContent/master/nugeticon.png
          icon-dst: ./deployment/nugeticon.png
          nuget-key: ${{ secrets.NUGET_KEY }}
